language: android

env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

jdk: oraclejdk8
# android-24需要jdk8+来编译

android:
  components:
    - tools
    - platform-tools
    - build-tools-24.0.1
    - android-24
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

    #测试使用的系统镜像（其实使用下面的虚拟机就好了，这句不加也可以）
    - sys-img-armeabi-v7a-android-19

#这个我也不知道算什么，是因为使用gradlew命令运行的时候显示没有权限，google上查到的方法
before_install:
 - chmod +x gradlew

#下面是在官方文档上的标准写法，-no-skin是我google上查一些东西的时候加的
# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &